defaults:
  - model: cross_attention
  - data: default
  - trainer: default
  - override hydra/launcher: joblib
  - _self_

seed: 42
experiment_name: "abaw-cross-attention"

hydra:
  launcher:
    n_jobs: 1
